### PR TITLE
Issues #3 , Handling rounding issues

### PR DESCRIPTION
**Pull request by vishva007**
The reminder amount left is added back to fund total to be distributed later

### CODE REVIEW

**Comment by tonyin** [comment]
hey, thks for the pr

we need to handle the share paid out to each member first. if the fundTotal does not divide up evenly (within the allowed decimal places) among all members, then there will be a leftover. see https://github.com/tonyin/the-daio/pull/5/files#diff-bfd1318427572667a1986cac662c047bL189

**Comment by vishva007** [comment]
The leftover will be the reminder which will be filled back again in fundTotal for the next distribution. Am I missing something ?

**Comment by tonyin** [comment]
i meant that we should first handle the division on line 189, reproduced here: `uint share = fundTotal / membersTotal;`

i am not sure what happens if the division does not handle cleanly

**Comment by vishva007** [comment]
Added a commit change for checking division with zero

**Comment by tonyin** [comment]
Put another way: if the fund has 100, and there are 3 members, how much does each member get? What does 100/3 return each time it is executed? Ideally each member gets the same amount to the number of significant digits that the token allows (can just use ETH for now) and the remainder will remain in the daio.

**Pull request closed without merging**
